dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
- psql -U postgres -c "ALTER USER decide Superuser"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
before_script:
 - cp local_settings.travis.py local_settings.py
script:
- cd decide
- python ./manage.py makemigrations
- python ./manage.py migrate
- python ./manage.py test --keepdb
