# Generated by Django 2.0 on 2020-01-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20200119_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
